const allStrings = {
  en: {
    // App.js / Layout strings
    appLogo: "MediGuide",
    navHome: "Home",
    navAssistant: "AI Assistant",
    navPredictions: "History",
    navDoctors: "Doctors",
    navReports: "Reports",
    navNews: "Medical News",
    navSettings: "Settings",
    navSectionNavigation: "Navigation",
    navSectionAccount: "Account",
    dateLabel: "Date",
    medicalSummary: "Medical Summary",
    statusLabel: "Status",
    generated: "Generated",
    downloadPdf: "Download PDF",
    noReportsFound: "No reports found",
    generateReportDesc: "Generate a report by booking an appointment in the Assistant tab.",
    appHeader: "Disease Prediction System",
    welcomeUser: "Welcome, ",
    logout: "Logout",
    predictionHistoryTitle: "Patient History",
    noPredictions: "No predictions recorded yet.",
    caseIdPrefix: "Case #",
    symptomsLabel: "Symptoms:",
    resultLabel: "Result:",
    viewDetails: "View Details",
    doctorsListTitle: "Doctors List",
    findSpecialist: "Find a specialist",
    findSpecialistDesc: "Complete a diagnosis in the Assistant tab for recommendations.",
    goToAssistant: "Go to Assistant",
    settingsTitle: "App Settings",
    settingsComingSoon: "Settings saved successfully.",

    // Login strings
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your health dashboard",
    createAccount: "Create Account",
    joinToday: "Join MediGuide today",
    fullName: "Full Name",
    emailAddr: "Email Address",
    password: "Password",
    signInBtn: "Sign In",
    registerBtn: "Register for free",
    alreadyHaveAcc: "Already have an account?",
    noAcc: "Don't have an account?",
    signInInstead: "Sign in instead",
    brandTitle: "Your AI Health Companion",
    brandDesc: "Get instant disease insights, AI-powered symptom analysis, and connect with the right specialists—all in one place.",

    // Home strings
    heroTitle: "Healthcare Decision Support System",
    heroSubtitle: "MediGuide helps you analyse symptoms, get AI-powered disease predictions, and connect with the right doctors — all in one seamless experience.",
    startDiagnosis: "Start Diagnosis",
    viewHistory: "View History",
    diseasesDetected: "Diseases detected",
    uptime: "Uptime",
    languages: "Languages",
    aboutTitle: "About MediGuide",
    aboutDesc: "MediGuide is a healthcare decision-support system where AI is used as one component to assist in disease prediction based on symptoms. It integrates rule-based matching, machine learning, and NLP to provide reliable, multi-language health guidance.",
    howItWorks: "How It Works",
    step1Title: "Enter Symptoms",
    step1Desc: "Type or speak your symptoms in English, Hindi, or Tamil.",
    step2Title: "AI Analysis",
    step2Desc: "Our ML engine processes inputs using NLP & rule-based matching.",
    step3Title: "Get Prediction",
    step3Desc: "Top possible diseases are shown with confidence scores.",
    step4Title: "Find Doctors",
    step4Desc: "Relevant specialist doctors are recommended near you.",
    keyFeatures: "Key Features",

    // Assistant / SymptomForm strings
    assistantTitle: "Smart Symptom Analysis",
    assistantSubtitle: "Describe how you feel, and our AI will provide a preliminary analysis and suggest specialists.",
    assistantHeader: "AI Health Assistant",
    assistantSubHeader: "Smart Analysis",
    speakOrTypePlaceholder: "Describe your symptoms (e.g., Fever, Headache, Fatigue)...",
    voiceBtn: "Voice Input",
    predictBtn: "Analyze Symptoms",
    pleaseEnterSymptoms: "Please enter or speak your symptoms first.",
    predictionFailed: "Analysis failed. Please try again.",
    errorFetchingSlots: "Error fetching available time slots.",
    fillAllDetailsAlert: "Please fill in all patient details and select a time slot.",
    bookingSuccessfulAlert: "Appointment booked successfully! PDF generated.",
    slotAlreadyBookedAlert: "This slot is already booked. Please choose another.",
    appointmentCancelledAlert: "Appointment cancelled successfully.",
    reschedulePromptDate: "Enter new date (YYYY-MM-DD):",
    reschedulePromptTime: "Enter new time (e.g., 10:00 AM):",
    appointmentRescheduledAlert: "Appointment rescheduled successfully! New PDF generated.",
    predictionResultTitle: "Primary Analysis Results",
    recommendedDoctorsTitle: "Recommended Specialists Nearby",
    patientNamePlaceholder: "Patient Full Name",
    phonePlaceholder: "Phone Number",
    selectSlotDefault: "Select Time Slot",
    slotFull: "(Full)",
    bookBtn: "Confirm Booking",
    cancelBtn: "Cancel",
    rescheduleBtn: "Reschedule",

    // Chatbox strings
    botInitialGreeting: "Hello 👋 I am your AI Health Assistant.\nPlease tell me your symptoms.",
    speechNotSupported: "Speech recognition not supported.",
    analyzingSymptoms: "🔍 Analyzing symptoms...",
    analyzingSymptomsStatus: "🔍 Analyzing symptoms...",
    possibleDisease: "🦠 Possible Disease: ",
    confidenceLabel: "📊 Confidence: ",
    medicalAlert: "🚨 MEDICAL ALERT",
    possibleCondition: "Possible Condition: ",
    emergencyAttention: "⚠ Emergency medical attention needed.",
    descriptionLabel: "📖 Description:",
    precautionsLabel: "🛡 Precautions:",
    healthTipLabel: "💡 Health Tip:",
    consultDoctor: "📞 Consult a doctor.",
    finalPrediction: "✅ Final Prediction",
    patientSummary: "👤 Summary",
    patientName: "Name: ",
    patientAge: "Age: ",
    patientGender: "Gender: ",
    patientDuration: "Duration: ",
    patientDays: " days",
    followUp: "🩺 Follow-up:",
    preliminaryPrediction: "⚠ AI-based preliminary prediction.",
    defaultReply: "Please describe symptoms.",
    serverError: "⚠ Server error.",
    analyzingSymptomStatus: "🤖 AI analyzing...",
    yes: "Yes",
    no: "No",
    inputPlaceholder: "Fever, cough...",
    listening: "🎙 Listening...",
    speak: "🎤 Speak",
    send: "Send",
    quickReplyLabel: "Quick reply:",

    // Dashboard strings
    dashboardTitle: "AI Health Assistant Dashboard",
    dashboardDescription: "MediGuide analyzes symptoms and predicts diseases using AI models.",
    featuresTitle: "Our Features",
    featureDiseasePredictionTitle: "Prediction",
    featureDiseasePredictionDesc: "Predict diseases using ML.",
    featureAiChatAssistantTitle: "AI Assistant",
    featureAiChatAssistantDesc: "Interactive AI for health.",
    featureDoctorRecommendationTitle: "Doctors",
    featureDoctorRecommendationDesc: "Suggest best doctors.",
    featureAppointmentBookingTitle: "Booking",
    featureAppointmentBookingDesc: "Book appointments directly.",
    featureMedicalReportsTitle: "Reports",
    featureMedicalReportsDesc: "Download PDF reports.",
    featureMultilingualSupportTitle: "Multilingual",
    featureMultilingualSupportDesc: "Multiple languages supported."
  },
  ta: {
    appLogo: "மெடிகைடு",
    navHome: "முகப்பு",
    navAssistant: "AI உதவியாளர்",
    navPredictions: "வரலாறு",
    navDoctors: "மருத்துவர்கள்",
    navReports: "அறிக்கைகள்",
    navNews: "மருத்துவ செய்திகள்",
    navSettings: "அமைப்புகள்",
    navSectionNavigation: "வழிசெலுத்தல்",
    navSectionAccount: "கணக்கு",
    dateLabel: "தேதி",
    medicalSummary: "மருத்துவ சுருக்கம்",
    statusLabel: "நிலை",
    generated: "உருவாக்கப்பட்டது",
    downloadPdf: "PDF பதிவிறக்கவும்",
    noReportsFound: "அறிக்கைகள் எதுவும் இல்லை",
    generateReportDesc: "உதவியாளர் பகுதியில் ஒரு அப்பாயிண்ட்மெண்ட் முன்பதிவு செய்வதன் மூலம் அறிக்கையை உருவாக்கவும்.",
    appHeader: "நோய் கணிப்பு அமைப்பு",
    welcomeUser: "வரவேற்கிறோம், ",
    logout: "வெளியேறு",
    predictionHistoryTitle: "நோயாளி கணிப்பு வரலாறு",
    noPredictions: "கணிப்புகள் ஏதும் இல்லை.",
    caseIdPrefix: "வழக்கு #",
    symptomsLabel: "அறிகுறிகள்:",
    resultLabel: "முடிவு:",
    viewDetails: "விவரங்களை காண்க",
    doctorsListTitle: "மருத்துவர்கள் பட்டியல்",
    findSpecialist: "நிபுணரைத் தேடுங்கள்",
    findSpecialistDesc: "பரிந்துரைகளைப் பெற உதவியாளர் பகுதியில் கணிப்பை முடிக்கவும்.",
    goToAssistant: "உதவியாளருக்குச் செல்லவும்",
    settingsTitle: "பயன்பாட்டு அமைப்புகள்",
    settingsComingSoon: "அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டன.",

    loginTitle: "மீண்டும் வருக",
    loginSubtitle: "உங்கள் சுகாதார போர்டலில் நுழையவும்",
    createAccount: "கணக்கை உருவாக்கவும்",
    joinToday: "இன்று மெடிகைடில் இணையுங்கள்",
    fullName: "முழு பெயர்",
    emailAddr: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    signInBtn: "உள்நுழைக",
    registerBtn: "இலவசமாக பதிவு செய்யுங்கள்",
    alreadyHaveAcc: "ஏற்கனவே கணக்கு உள்ளதா?",
    noAcc: "கணக்கு இல்லையா?",
    signInInstead: "அதற்கு பதிலாக உள்நுழையவும்",
    brandTitle: "உங்கள் AI சுகாதார உதவியாளர்",
    brandDesc: "உடனடி நோய் நுண்ணறிவு, AI-அடிப்படையிலான அறிகுறி பகுப்பாய்வு மற்றும் சரியான நிபுணர்களுடன் தொடர்பு கொள்ளுங்கள்—எல்லாம் ஒரே இடத்தில்.",

    heroTitle: "சுகாதார முடிவு ஆதரவு அமைப்பு",
    heroSubtitle: "மெடிகைடு அறிகுறிகளை பகுப்பாய்வு செய்யவும், AI-அடிப்படையிலான நோய் கணிப்புகளைப் பெறவும் மற்றும் சரியான மருத்துவர்களுடன் தொடர்பு கொள்ளவும் உதவுகிறது.",
    startDiagnosis: "கணிப்பைத் தொடங்கு",
    viewHistory: "வரலாற்றைக் காண்க",
    diseasesDetected: "நோய்கள் கண்டறியப்பட்டன",
    uptime: "செயல்பாட்டு நேரம்",
    languages: "மொழிகள்",
    aboutTitle: "மெடிகைடு பற்றி",
    aboutDesc: "மெடிகைடு என்பது ஒரு சுகாதார முடிவு-ஆதரவு அமைப்பாகும், இங்கு அறிகுறிகளின் அடிப்படையில் நோய் கணிப்புக்கு உதவ AI பயன்படுத்தப்படுகிறது.",
    howItWorks: "இது எப்படி வேலை செய்கிறது",
    step1Title: "அறிகுறிகளை உள்ளிடவும்",
    step1Desc: "உங்கள் அறிகுறிகளை ஆங்கிலம், இந்தி அல்லது தமிழில் தட்டச்சு செய்யவும் அல்லது பேசவும்.",
    step2Title: "AI பகுப்பாய்வு",
    step2Desc: "எங்கள் ML இயந்திரம் NLP மற்றும் விதி அடிப்படையிலான பொருத்தத்தைப் பயன்படுத்தி உள்ளீடுகளைச் செயலாக்குகிறது.",
    step3Title: "கணிப்பைப் பெறுங்கள்",
    step3Desc: "சாத்தியமான நோய்கள் நம்பிக்கை மதிப்பெண்களுடன் காட்டப்படுகின்றன.",
    step4Title: "மருத்துவர்களைக் கண்டறியவும்",
    step4Desc: "உங்களுக்கு அருகிலுள்ள பொருத்தமான நிபுணர் மருத்துவர்கள் பரிந்துரைக்கப்படுகிறார்கள்.",
    keyFeatures: "முக்கிய அம்சங்கள்",

    assistantTitle: "புத்திசாலித்தனமான அறிகுறி பகுப்பாய்வு",
    assistantSubtitle: "உங்கள் உணர்வை விவரிக்கவும், எங்கள் AI பூர்வாங்க பகுப்பாய்வை வழங்கி நிபுணர்களைப் பரிந்துரைக்கும்.",
    assistantHeader: "AI சுகாதார உதவியாளர்",
    assistantSubHeader: "புத்திசாலித்தனமான பகுப்பாய்வு",
    speakOrTypePlaceholder: "உங்கள் அறிகுறிகளை விவரிக்கவும் (எ.கா., காய்ச்சல், தலைவலி)...",
    voiceBtn: "குரல் உள்ளீடு",
    predictBtn: "அறிகுறிகளை பகுப்பாய்வு செய்",
    pleaseEnterSymptoms: "முதலில் உங்கள் அறிகுறிகளை உள்ளிடவும் அல்லது பேசவும்.",
    predictionFailed: "பகுப்பாய்வு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    errorFetchingSlots: "காலியான நேரங்களை பெறுவதில் பிழை.",
    fillAllDetailsAlert: "நோயாளியின் அனைத்து விவரங்களையும் பூர்த்தி செய்து நேரத்தை தேர்வு செய்யவும்.",
    bookingSuccessfulAlert: "முன்பதிவு வெற்றிகரமாக முடிந்தது! PDF உருவாக்கப்பட்டது.",
    slotAlreadyBookedAlert: "இந்த நேரம் ஏற்கனவே முன்பதிவு செய்யப்பட்டுள்ளது. வேறு நேரத்தை தேர்வு செய்யவும்.",
    appointmentCancelledAlert: "முன்பதிவு வெற்றிகரமாக ரத்து செய்யப்பட்டது.",
    reschedulePromptDate: "புதிய தேதியை உள்ளிடவும் (YYYY-MM-DD):",
    reschedulePromptTime: "புதிய நேரத்தை உள்ளிடவும் (எ.கா., 10:00 AM):",
    appointmentRescheduledAlert: "தேதி வெற்றிகரமாக மாற்றப்பட்டது! புதிய PDF உருவாக்கப்பட்டது.",
    predictionResultTitle: "முதன்மை பகுப்பாய்வு முடிவுகள்",
    recommendedDoctorsTitle: "அருகிலுள்ள பரிந்துரைக்கப்பட்ட நிபுணர்கள்",
    patientNamePlaceholder: "நோயாளியின் முழு பெயர்",
    phonePlaceholder: "தொலைபேசி எண்",
    selectSlotDefault: "நேரத்தைத் தேர்ந்தெடுக்கவும்",
    slotFull: "(நிரம்பியது)",
    bookBtn: "முன்பதிவை உறுதி செய்",
    cancelBtn: "ரத்து செய்",
    rescheduleBtn: "தேதி மாற்று",

    botInitialGreeting: "வணக்கம் 👋 நான் உங்கள் AI உதவியாளர். உங்கள் அறிகுறிகளைக் கூறவும்.",
    speechNotSupported: "பேச்சு அங்கீகாரம் ஆதரிக்கப்படவில்லை.",
    analyzingSymptoms: "🔍 பகுப்பாய்வு செய்கிறது...",
    analyzingSymptomsStatus: "🔍 பகுப்பாய்வு செய்கிறது...",
    possibleDisease: "🦠 சாத்தியமான நோய்: ",
    confidenceLabel: "📊 நம்பிக்கை: ",
    medicalAlert: "🚨 மருத்துவ எச்சரிக்கை",
    possibleCondition: "சாத்தியமான நிலை: ",
    emergencyAttention: "⚠ அவசர சிகிச்சை தேவைப்படலாம்.",
    descriptionLabel: "📖 விளக்கம்:",
    precautionsLabel: "🛡 முன்னெச்சரிக்கைகள்:",
    healthTipLabel: "💡 ஆரோக்கிய குறிப்பு:",
    consultDoctor: "📞 மருத்துவரை அணுகவும்.",
    finalPrediction: "✅ இறுதி கணிப்பு",
    patientSummary: "👤 நோயாளியின் சுருக்கம்",
    patientName: "பெயர்: ",
    patientAge: "வயது: ",
    patientGender: "பாலினம்: ",
    patientDuration: "காலம்: ",
    patientDays: " நாட்கள்",
    followUp: "🩺 பின்தொடர்தல்:",
    preliminaryPrediction: "⚠ AI அடிப்படையிலான கணிப்பு மட்டுமே. அறிகுறிகளைத் தெளிவாகக் கூறவும்.",
    defaultReply: "அறிகுறிகளைத் தெளிவாகக் கூறவும்.",
    serverError: "⚠ பிழை ஏற்பட்டது.",
    analyzingSymptomStatus: "🤖 AI பகுப்பாய்வு செய்கிறது...",
    yes: "ஆம்",
    no: "இல்லை",
    inputPlaceholder: "காய்ச்சல், இருமல்...",
    listening: "🎙 கேட்கிறது...",
    speak: "🎤 பேசவும்",
    send: "அனுப்பு",
    quickReplyLabel: "விரைவான பதில்:",

    dashboardTitle: "AI சுகாதார உதவியாளர்",
    dashboardDescription: "மெடிகைடு அறிகுறிகளை பகுப்பாய்வு செய்து நோய்களைக் கணிக்கும்.",
    featuresTitle: "எங்கள் அம்சங்கள்",
    featureDiseasePredictionTitle: "நோய் கணிப்பு",
    featureDiseasePredictionDesc: "ML மூலம் நோய்களைக் கணிக்கும்.",
    featureAiChatAssistantTitle: "AI உதவியாளர்",
    featureAiChatAssistantDesc: "ஊடாடும் AI உதவியாளர்.",
    featureDoctorRecommendationTitle: "மருத்துவர் பரிந்துரை",
    featureDoctorRecommendationDesc: "சிறந்த மருத்துவர்களை பரிந்துரைக்கும்.",
    featureAppointmentBookingTitle: "முன்பதிவு",
    featureAppointmentBookingDesc: "நேரடியாக முன்பதிவு செய்யலாம்.",
    featureMedicalReportsTitle: "அறிக்கைகள்",
    featureMedicalReportsDesc: "PDF அறிக்கைகளை பதிவிறக்கவும்.",
    featureMultilingualSupportTitle: "பலமொழி ஆதரவு",
    featureMultilingualSupportDesc: "பல மொழிகளை ஆதரிக்கிறது."
  },
  hi: {
    appLogo: "मेडिगाइड",
    navHome: "होम",
    navAssistant: "AI सहायक",
    navPredictions: "इतिहास",
    navDoctors: "डॉक्टर",
    navReports: "रिपोर्ट",
    navNews: "मेडिकल न्यूज़",
    navSettings: "सेटिंग्स",
    navSectionNavigation: "नेविगेशन",
    navSectionAccount: "खाता",
    dateLabel: "तारीख",
    medicalSummary: "चिकित्सा सारांश",
    statusLabel: "स्थिति",
    generated: "तैयार किया गया",
    downloadPdf: "PDF डाउनलोड करें",
    noReportsFound: "कोई रिपोर्ट नहीं मिली",
    generateReportDesc: "सहायक टैब में अपॉइंटमेंट बुक करके एक रिपोर्ट तैयार करें।",
    appHeader: "रोग भविष्यवाणी प्रणाली",
    welcomeUser: "स्वागत है, ",
    logout: "लॉगआउट",
    predictionHistoryTitle: "रोगी भविष्यवाणी इतिहास",
    noPredictions: "अभी तक कोई भविष्यवाणी नहीं है।",
    caseIdPrefix: "मामला #",
    symptomsLabel: "लक्षण:",
    resultLabel: "परिणाम:",
    viewDetails: "विवरण देखें",
    doctorsListTitle: "डॉक्टरों की सूची",
    findSpecialist: "विशेषज्ञ खोजें",
    findSpecialistDesc: "सिफारिशें पाने के लिए सहायक टैब में विश्लेषण पूरा करें।",
    goToAssistant: "सहायक पर जाएं",
    settingsTitle: "ऐप सेटिंग्स",
    settingsComingSoon: "सेटिंग्स सफलतापूर्वक सहेजी गईं।",

    loginTitle: "वापसी पर स्वागत है",
    loginSubtitle: "अपने स्वास्थ्य डैशबोर्ड में साइन इन करें",
    createAccount: "खाता बनाएं",
    joinToday: "आज ही मेडिगाइड से जुड़ें",
    fullName: "पूरा नाम",
    emailAddr: "ईमेल पता",
    password: "पासवर्ड",
    signInBtn: "साइन इन करें",
    registerBtn: "मुफ्त में पंजीकरण करें",
    alreadyHaveAcc: "पहले से ही खाता है?",
    noAcc: "खाता नहीं है?",
    signInInstead: "इसके बजाय साइन इन करें",
    brandTitle: "आपका AI स्वास्थ्य साथी",
    brandDesc: "त्वरित रोग अंतर्दृष्टि, AI-संचालित लक्षण विश्लेषण प्राप्त करें और सही विशेषज्ञों से जुड़ें—सब एक ही स्थान पर।",

    heroTitle: "स्वास्थ्य निर्णय समर्थन प्रणाली",
    heroSubtitle: "मेडिगाइड आपको लक्षणों का विश्लेषण करने, AI-संचालित रोग भविष्यवाणियां प्राप्त करने और सही डॉक्टरों से जुड़ने में मदद करता है।",
    startDiagnosis: "निदान शुरू करें",
    viewHistory: "इतिहास देखें",
    diseasesDetected: "रोगों का पता लगा",
    uptime: "अपटाइम",
    languages: "भाषाएं",
    aboutTitle: "मेडिगाइड के बारे में",
    aboutDesc: "मेडिगाइड एक स्वास्थ्य निर्णय-समर्थन प्रणाली है जहाँ लक्षणों के आधार पर रोग की भविष्यवाणी में सहायता के लिए AI का उपयोग किया जाता है।",
    howItWorks: "यह कैसे काम करता है",
    step1Title: "लक्षण दर्ज करें",
    step1Desc: "अंग्रेजी, हिंदी या तमिल में अपने लक्षण टाइप करें या बोलें।",
    step2Title: "AI विश्लेषण",
    step2Desc: "हमारा ML इंजन NLP और नियम-आधारित मिलान का उपयोग करके इनपुट को संसाधित करता है।",
    step3Title: "भविष्यवाणी प्राप्त करें",
    step3Desc: "संभावित रोगों को विश्वास स्कोर के साथ दिखाया गया है।",
    step4Title: "डॉक्टर खोजें",
    step4Desc: "आपके पास संबंधित विशेषज्ञ डॉक्टरों की सिफारिश की जाती है।",
    keyFeatures: "प्रमुख विशेषताएं",

    assistantTitle: "स्मार्ट लक्षण विश्लेषण",
    assistantSubtitle: "बताएं कि आप कैसा महसूस कर रहे हैं, और हमारा AI प्रारंभिक विश्लेषण प्रदान करेगा और विशेषज्ञों का सुझाव देगा।",
    assistantHeader: "AI स्वास्थ्य सहायक",
    assistantSubHeader: "स्मार्ट विश्लेषण",
    speakOrTypePlaceholder: "अपने लक्षणों का वर्णन करें (जैसे, बुखार, सिरदर्द)...",
    voiceBtn: "आवाज इनपुट",
    predictBtn: "लक्षणों का विश्लेषण करें",
    pleaseEnterSymptoms: "कृपया पहले अपने लक्षण दर्ज करें या बोलें।",
    predictionFailed: "विश्लेषण विफल रहा। कृपया पुनः प्रयास करें।",
    errorFetchingSlots: "उपलब्ध समय स्लॉट प्राप्त करने में त्रुटि।",
    fillAllDetailsAlert: "कृपया रोगी के सभी विवरण भरें और समय स्लॉट चुनें।",
    bookingSuccessfulAlert: "अपॉइंटमेंट सफलतापूर्वक बुक हो गया! PDF तैयार है।",
    slotAlreadyBookedAlert: "यह स्लॉट पहले से ही बुक है। कृपया दूसरा चुनें।",
    appointmentCancelledAlert: "अपॉइंटमेंट सफलतापूर्वक रद्द कर दिया गया।",
    reschedulePromptDate: "नई तारीख दर्ज करें (YYYY-MM-DD):",
    reschedulePromptTime: "नया समय दर्ज करें (जैसे, 10:00 AM):",
    appointmentRescheduledAlert: "अपॉइंटमेंट सफलतापूर्वक पुनर्निर्धारित किया गया! नया PDF तैयार है।",
    predictionResultTitle: "प्राथमिक विश्लेषण परिणाम",
    recommendedDoctorsTitle: "पास के अनुशंसित विशेषज्ञ",
    patientNamePlaceholder: "रोगी का पूरा नाम",
    phonePlaceholder: "फ़ोन नंबर",
    selectSlotDefault: "समय स्लॉट चुनें",
    slotFull: "(भरा हुआ)",
    bookBtn: "बुकिंग की पुष्टि करें",
    cancelBtn: "रद्द करें",
    rescheduleBtn: "पुनर्निर्धारित करें",

    botInitialGreeting: "नमस्ते 👋 मैं आपका AI स्वास्थ्य सहायक हूँ। कृपया अपने लक्षण बताएं।",
    speechNotSupported: "स्पीच रिकग्निशन समर्थित नहीं है।",
    analyzingSymptoms: "🔍 विश्लेषण हो रहा है...",
    analyzingSymptomsStatus: "🔍 विश्लेषण हो रहा है...",
    possibleDisease: "🦠 संभावित रोग: ",
    confidenceLabel: "📊 विश्वास: ",
    medicalAlert: "🚨 मेडिकल अलर्ट",
    possibleCondition: "संभावित स्थिति: ",
    emergencyAttention: "⚠ तत्काल डॉक्टर की जरूरत हो सकती है।",
    descriptionLabel: "📖 विवरण:",
    precautionsLabel: "🛡 सावधानियां:",
    healthTipLabel: "💡 स्वास्थ्य टिप:",
    consultDoctor: "📞 डॉक्टर से सलाह लें।",
    finalPrediction: "✅ अंतिम भविष्यवाणी",
    patientSummary: "👤 रोगी सारांश",
    patientName: "नाम: ",
    patientAge: "उम्र: ",
    patientGender: "लिंग: ",
    patientDuration: "अवधि: ",
    patientDays: " दिन",
    followUp: "🩺 फॉलो-अप:",
    preliminaryPrediction: "⚠ AI-आधारित केवल प्रारंभिक भविष्यवाणी।",
    defaultReply: "लक्षणों का वर्णन करें।",
    serverError: "⚠ सर्वर त्रुटि।",
    analyzingSymptomStatus: "🤖 AI विश्लेषण कर रहा है...",
    yes: "हाँ",
    no: "नहीं",
    inputPlaceholder: "बुखार, खांसी...",
    listening: "🎙 सुन रहा हूँ...",
    speak: "🎤 बोलें",
    send: "भेजें",
    quickReplyLabel: "त्वरित उत्तर:",

    dashboardTitle: "AI स्वास्थ्य सहायक डैशबोर्ड",
    dashboardDescription: "मेडिगाइड लक्षणों का विश्लेषण करता है और रोगों की भविष्यवाणी करता है।",
    featuresTitle: "प्रमुख विशेषताएं",
    featureDiseasePredictionTitle: "भविष्यवाणी",
    featureDiseasePredictionDesc: "ML मॉडल के साथ भविष्यवाणी करें।",
    featureAiChatAssistantTitle: "AI सहायक",
    featureAiChatAssistantDesc: "इंटरैक्टिव AI सहायक।",
    featureDoctorRecommendationTitle: "विशेषज्ञ",
    featureDoctorRecommendationDesc: "सर्वोत्तम डॉक्टरों का सुझाव दें।",
    featureAppointmentBookingTitle: "अपॉइंटमेंट",
    featureAppointmentBookingDesc: "सीधे अपॉइंटमेंट बुक करें।",
    featureMedicalReportsTitle: "रिपोर्ट",
    featureMedicalReportsDesc: "PDF रिपोर्ट डाउनलोड करें।",
    featureMultilingualSupportTitle: "बहुभाषी",
    featureMultilingualSupportDesc: "कई भाषाओं का समर्थन करता है।"
  }
};

const getStrings = () => {
  const currentLang = localStorage.getItem("app_lang") || "en";
  return allStrings[currentLang] || allStrings.en;
};

const strings = getStrings();

export const refreshStrings = () => getStrings();
export { allStrings };
export default strings;
